### ISSUE TITLE
Fixed Supply of Listing Rewards (45%) is a Problem

### ISSUE THREAD

**Issue by jnmclarty** [rexmls/whitepaper#2]
This is the second issue in a series I'm raising, feel free to ignore me until a few more are posted.  See #1 first.

Creating the supply of listing rewards at the onset, or even something based in units of time, or per a schedule, with assumptions about number of listings is an oversimplification.

The network protocol should create tokens for new listings that get approved & verified by the network.  It should be infinite, or capped in a rule that could be derived from a comprehensive upper-bound limit. Eg. "Max limit it 8B + 2% per year" (Assume every person on earth wants to list a property once per year.

Token-owners can make assumptions about the "inflation" rate, and new token issuance if they want/need to.  In general, more actual listings on the network, means the network effects are increasing.

Implementation ideas will of course be more tricky.

**Comment by rexmls** [comment]
Due to previous complaints from the community we have included "projections" of what kind of usage the platform may encounter, and from that we have derived the size of the pool of funds and reward ratios etc.

But basically it operates as you have suggested, the rewards are purely based on participation.  But the rewards are to come from a finite pool of pre-allocated tokens that was pre-determined to appease the community.
